pattern = 'v0.1.%d'
types = ["Cargo"]
message-template = "Releasing {version}."

[artifact.linux]
paths = {inc = "linux/ns-net-bridge"}
compress = { name = "ns-net-bridge-x86_64.tar.gz", format = "tgz" }
target = "GitHub"
