name: Publish Image

on:
  push:
    branches:
    - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: do-build
      run: |
          mkdir ~/bin
          curl --location https://github.com/ethankhall/crom/releases/download/v0.2.4/crom-linux-musl.tar.gz | tar -xvz  -C ~/bin
          chmod +x ~/bin/crom
          ~/bin/crom update-version --pre-release release
    - uses: actions-rs/cargo@v1
      with:
        command: check
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: linux-artifacts
        path: target/release/ns-net-bridge
  release:
    runs-on: ubuntu-latest
    needs:
      - build-linux
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: linux-artifacts
          path: artifacts/linux
      - name: Create release
        run: |
          mkdir ~/bin
          curl --location https://github.com/ethankhall/crom/releases/download/v0.2.4/crom-linux-musl.tar.gz | tar -xvz  -C ~/bin
          chmod +x ~/bin/crom
          ~/bin/crom tag-version --source local,github --ignore-changes
          ~/bin/crom upload-artifacts --root-artifact-path=./artifacts linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      